# Generated by Django 5.2.9 on 2026-01-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('industryCode', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(choices=[('USA', 'United States'), ('JP', 'Japan'), ('UK', 'United Kingdom'), ('AUS', 'Australia'), ('GER', 'Germany'), ('FR', 'France'), ('IT', 'Italy'), ('CN', 'China'), ('KOR', 'South Korea'), ('RUS', 'Russia')], max_length=3)),
                ('is_defunct', models.BooleanField(default=False)),
                ('industries', models.ManyToManyField(to='core.industry')),
            ],
        ),
    ]
