# Generated by Django 5.2.9 on 2026-01-04 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_carmodel_facelift'),
    ]

    operations = [
        migrations.RenameField(
            model_name='industry',
            old_name='name',
            new_name='Industry_Type',
        ),
        migrations.RenameField(
            model_name='industry',
            old_name='industryCode',
            new_name='industry_Code',
        ),
    ]
