# Generated by Django 5.2.9 on 2026-01-04 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_name_industry_industry_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facelift',
            name='changes_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='facelift',
            name='facelift_year',
            field=models.PositiveIntegerField(default=2016),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CarBodyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_type', models.CharField(max_length=100, unique=True)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_types', to='core.carmodel')),
            ],
        ),
    ]
