# Generated by Django 5.2.9 on 2026-01-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_facelift_changes_description_facelift_facelift_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbodytype',
            name='body_type',
            field=models.CharField(choices=[('SEDAN', 'Sedan'), ('WAGON', 'Wagon'), ('SUV', 'SUV'), ('HATCHBACK', 'Hatchback'), ('COUPE', 'Coupe'), ('CONVERTIBLE', 'Convertible'), ('SPORTS', 'Sports Car'), ('SUPER', 'Supercar'), ('LUXURY', 'Luxury Car'), ('CONCEPT', 'Concept Car'), ('PICKUP', 'Pickup Truck'), ('VAN', 'Van/Minivan')], max_length=20),
        ),
    ]
