# Generated by Django 5.2.9 on 2026-01-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_carbodytype_body_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbodytype',
            name='door_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carbodytype',
            name='seat_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
