# Generated by Django 5.2.9 on 2026-01-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_carbodytype_door_count_carbodytype_seat_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbodytype',
            name='original_offer',
            field=models.BooleanField(default=True),
        ),
    ]
