# Generated by Django 5.2.9 on 2026-01-04 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_carbodytype_original_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carbodytype',
            old_name='original_offer',
            new_name='offered_from_new',
        ),
    ]
