# Generated by Django 5.2.9 on 2026-01-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_original_offer_carbodytype_offered_from_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbodytype',
            name='bodystyle_end_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carbodytype',
            name='bodystyle_start_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
