# Generated by Django 5.2.9 on 2026-01-04 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_carbodytype_bodystyle_end_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbodytype',
            name='body_type',
            field=models.CharField(choices=[('SEDAN', 'Sedan'), ('WAGON', 'Wagon'), ('SUV', 'SUV'), ('HATCHBACK', 'Hatchback'), ('COMPACT', 'Compact Car'), ('COUPE', 'Coupe'), ('CONVERTIBLE', 'Convertible'), ('SPORTS', 'Sports Car'), ('SUPER', 'Supercar'), ('LUXURY', 'Luxury Car'), ('CONCEPT', 'Concept Car'), ('PICKUP', 'Pickup Truck'), ('VAN', 'Van/Minivan')], max_length=20),
        ),
        migrations.CreateModel(
            name='CarEngine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_type', models.CharField(choices=[('PETROL', 'Internal Combustion Engine - Petrol'), ('DIESEL', 'Internal Combustion Engine - Diesel'), ('EV', 'Electric Vehicle'), ('HYBRID', 'Hybrid - Petrol/Electric'), ('DIESEL_HYBRID', 'Hybrid - Diesel/Electric'), ('HYDROGEN', 'Hydrogen Fuel Cell')], max_length=20)),
                ('displacement_cc', models.PositiveIntegerField()),
                ('cylinders', models.PositiveIntegerField()),
                ('horsepower', models.PositiveIntegerField()),
                ('torque_nm', models.PositiveIntegerField()),
                ('turbocharged', models.BooleanField(default=False)),
                ('supercharged', models.BooleanField(default=False)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engines', to='core.carmodel')),
            ],
        ),
    ]
