# Generated by Django 5.2.9 on 2026-01-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_carbodytype_body_type_carengine'),
    ]

    operations = [
        migrations.AddField(
            model_name='carengine',
            name='bodystyle_end_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carengine',
            name='bodystyle_start_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carengine',
            name='offered_from_new',
            field=models.BooleanField(default=True),
        ),
    ]
