# Generated by Django 5.2.9 on 2026-01-04 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_carengine_bodystyle_end_year_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carengine',
            old_name='bodystyle_end_year',
            new_name='engine_end_year',
        ),
        migrations.RenameField(
            model_name='carengine',
            old_name='bodystyle_start_year',
            new_name='engine_start_year',
        ),
    ]
