# Generated by Django 5.2.9 on 2026-01-04 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_bodystyle_end_year_carengine_engine_end_year_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carengine',
            old_name='torque_nm',
            new_name='torque_lbft',
        ),
    ]
