# Generated by Django 5.2.9 on 2026-01-04 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_torque_nm_carengine_torque_lbft'),
    ]

    operations = [
        migrations.AddField(
            model_name='carengine',
            name='facelift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='engines', to='core.facelift'),
        ),
        migrations.AddField(
            model_name='carengine',
            name='offered_from_facelift',
            field=models.BooleanField(default=False),
        ),
    ]
