# Generated by Django 5.2.9 on 2026-01-04 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_carengine_facelift_carengine_offered_from_facelift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carengine',
            name='facelift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facelifts', to='core.facelift'),
        ),
    ]
