# Generated by Django 5.2.9 on 2026-01-04 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_carengine_facelift'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModelTrims',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trim_name', models.CharField(max_length=100)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trims', to='core.carmodel')),
            ],
        ),
    ]
