# Generated by Django 5.2.9 on 2026-01-04 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_carmodeltrims'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodeltrims',
            name='trim_engine',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='trim_engines', to='core.carengine'),
            preserve_default=False,
        ),
    ]
