# Generated by Django 5.2.9 on 2026-01-04 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_carmodeltrims_trim_engine'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarModelTrims',
            new_name='CarModelTrim',
        ),
    ]
