# Generated by Django 5.2.9 on 2026-01-04 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_rename_carmodeltrims_carmodeltrim'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodeltrim',
            name='trim_body_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trim_body_types', to='core.carbodytype'),
            preserve_default=False,
        ),
    ]
