# Generated by Django 5.2.9 on 2026-01-04 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_carmodeltrim_trim_body_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodeltrim',
            name='trim_body_type',
        ),
    ]
