# Generated by Django 5.2.9 on 2026-01-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_carmodeltrim_trim_body_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodeltrim',
            name='trim_body_type',
        ),
        migrations.AddField(
            model_name='carmodeltrim',
            name='trim_body_types',
            field=models.ManyToManyField(related_name='trims', to='core.carbodytype'),
        ),
    ]
